### ISSUE TITLE
"cart_func" is nil

### ISSUE THREAD

**Issue by FaceDeer** [cyian-1756/railtest#2]
Trying to place carts results in a nil dereference crash, there's no "cart_func" container to hold the is_rail function in func.lua.

**Comment by cyian-1756** [comment]
This strangely works on my install, what version of minetest, and minetest_game are you using? Do you have the cart mod install?

**Comment by cyian-1756** [comment]
I seem to have fixed the issue in my last push (now only `is_rail` is used)

**Comment by FaceDeer** [comment]
I'm using the version of minetest_game that comes with 0.4.16 and it includes a carts mod.

Syncing to latest railtest seems to fix the nil dereference problem, thanks.
